//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanKhach
    {
        public DoanKhach()
        {
            this.DSKhachTheoDoans = new HashSet<DSKhachTheoDoan>();
        }
    
        public int Id { get; set; }
        public string TenGoi { get; set; }
        public System.DateTime NgayKhoiHanh { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<int> TongKS { get; set; }
        public Nullable<int> TongAn { get; set; }
        public Nullable<int> TongPT { get; set; }
        public Nullable<int> TongKhac { get; set; }
        public int TourId { get; set; }
    
        public virtual ICollection<DSKhachTheoDoan> DSKhachTheoDoans { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
