//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSKhachTheoDoan
    {
        public int Id { get; set; }
        public int DoanKhachId { get; set; }
        public int KhachHangId { get; set; }
    
        public virtual DoanKhach DoanKhach { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
