//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaTour
    {
        public int Id { get; set; }
        public int Gia { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public int TourId { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
