//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DSKhachTheoDoans = new HashSet<DSKhachTheoDoan>();
        }
    
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public System.DateTime GioiTinh { get; set; }
    
        public virtual ICollection<DSKhachTheoDoan> DSKhachTheoDoans { get; set; }
    }
}
