//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDL
    {
        public LoaiDL()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int Id { get; set; }
        public string TenGoi { get; set; }
    
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
