//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tour> Tours { get; set; }
        public DbSet<LoaiDL> LoaiDLs { get; set; }
        public DbSet<GiaTour> GiaTours { get; set; }
        public DbSet<DiaDiem> DiaDiems { get; set; }
        public DbSet<TinhThanh> TinhThanhs { get; set; }
        public DbSet<CTTour> CTTours { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<DoanKhach> DoanKhaches { get; set; }
        public DbSet<NhiemVu> NhiemVus { get; set; }
        public DbSet<DSKhachTheoDoan> DSKhachTheoDoans { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<NhanVienTheoDoan> NhanVienTheoDoans { get; set; }
    }
}
